name: Check OSS history
on:
  - pull_request_target

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Check OSS history
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Print info
        env:
           BASE_REF: ${{ github.base_ref }}
        run: |
                echo "base ref: $BASE_REF"

      - name: Check OSS history
        uses: mbolivar-nordic/action-check-oss-history@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


          manifest-path: 'west.yml'
          checkout-path: 'ncs/nrf'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest, west'
          dnm-labels: 'DNM'
